import type { Plugin, App, Page } from 'vuepress'
import { existsSync, readFileSync, mkdirSync, writeFileSync } from 'fs'
import { join } from 'path'
import type {
  CopyPageOptions,
  ClientOptions,
  CopyPageI18n,
  CopyMeta,
  CopyTemplate,
} from './types.js'

// Re-export types for users
export type { CopyPageOptions, CopyPageI18n, CopyMeta, CopyTemplate }

// Store all markdown sources
const markdownSources: Record<string, string> = {}

export const copyPagePlugin = (options: CopyPageOptions = {}): Plugin => ({
  name: 'vuepress-plugin-copy-page',

  // Read markdown source for each page
  extendsPage(page: Page): void {
    const filePath = page.filePath
    if (filePath && existsSync(filePath)) {
      const content = readFileSync(filePath, 'utf-8')
      markdownSources[page.path] = content
    }
  },

  // Generate client config file to inject data
  clientConfigFile(app: App): string {
    const clientOptions: ClientOptions = {
      includes: options.includes ?? ['/posts/'],
      excludes: options.excludes ?? [],
      position: options.position ?? 'top-right',
      styleMode: options.styleMode ?? 'simple',
    }

    // Add new options if provided
    if (options.urlPrefix) {
      clientOptions.urlPrefix = options.urlPrefix
    }
    if (options.copyTemplate) {
      clientOptions.copyTemplate = options.copyTemplate
    }
    if (options.i18n) {
      clientOptions.i18n = options.i18n
    }

    // Serialize options, handling function templates
    const serializeOptions = (opts: ClientOptions): string => {
      const result: Record<string, unknown> = { ...opts }
      if (typeof opts.copyTemplate === 'function') {
        // Convert function to string for client-side use
        result.copyTemplate = `__FUNCTION__${opts.copyTemplate.toString()}__FUNCTION__`
      }
      return JSON.stringify(result)
    }

    const optionsJson = serializeOptions(clientOptions)

    const content = `// Auto-generated by vuepress-plugin-copy-page
import { defineClientConfig } from 'vuepress/client'

const options = ${optionsJson}
const sources = ${JSON.stringify(markdownSources)}

// Restore function templates
if (typeof options.copyTemplate === 'string' && options.copyTemplate.startsWith('__FUNCTION__') && options.copyTemplate.endsWith('__FUNCTION__')) {
  const fnStr = options.copyTemplate.slice(12, -12)
  options.copyTemplate = new Function('return ' + fnStr)()
}

if (typeof window !== 'undefined') {
  window.__COPY_PAGE_OPTIONS__ = options
  window.__MARKDOWN_SOURCES__ = sources
}

export default defineClientConfig({
  setup() {
    if (typeof window !== 'undefined') {
      window.__COPY_PAGE_OPTIONS__ = options
      window.__MARKDOWN_SOURCES__ = sources
    }
  }
})
`

    // Write to temp directory
    const tempDir = app.dir.temp()
    const configDir = join(tempDir, 'copy-page')
    const tempPath = join(configDir, 'data.ts')

    if (!existsSync(configDir)) {
      mkdirSync(configDir, { recursive: true })
    }
    writeFileSync(tempPath, content, 'utf-8')

    return tempPath
  },
})

export default copyPagePlugin
